[employee]
name = "John Doe"
age = 35

[job]
title = "Software Engineer"
department = "IT"
years_of_experience = 10

[address]
street = "123 Main St."
city = "San Francisco"
state = "CA"
zip = 94102

["game configuration"]
resolution_width = 1920
resolution_heightk = 1080
fullscreen = "true"
music_volume = 0.5
characters = "player, enemy, npd"

["web-site configuration"]
port = 1920
timeout = 30
